import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/root/Header";
import Footer from "@/components/root/Footer";
import AuthContext from "@/context/AuthContext";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col w-full`}>
        <AuthContext>
          <Header />
          <main className={"grow"}>{children}</main>
          <Footer />
        </AuthContext>
      </body>
    </html>
  );
}
